<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "media_essrrtpw"
 *
 * Auto generated by Extension Builder 2018-01-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Media ESSRRTPW',
    'description' => 'bb media',
    'category' => 'plugin',
    'author' => 'Pierre Wroblewski, Remy Torres, Sulivan Roirand, Evan Sevin',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
